### ISSUE TITLE
Documentation Error: heuristic not heuristicFunction

### ISSUE THREAD

**Issue by wlfio** [digitsensitive/astar-typescript#14]
A mistake in readme documentation

The documentation says that the heuristic function can be set with the `heuristicFunction` option in the constructor object, it is just `heuristic`

~~I thought of making a PR, but I feel dirty having a PR in a bigger project for just a "typo"~~

Edit: I have made a PR for a Cost feature for nodes, that also fixes this.

**Comment by digitsensitive** [comment]
Thanks for spotting and the PR. Since I currently not have the time to go through your PR I fixed this small problem in the documentation 👍🏼
