### ISSUE TITLE
only works once

### ISSUE THREAD

**Issue by krazyjakee** [digitsensitive/astar-typescript#2]
On first use, it seems fine.
On second, it always says `Path could not be created.`.

Here is an example of the bug in action: https://repl.it/@krazyjakee/StrangeShorttermSales

**Comment by digitsensitive** [comment]
Hello @krazyjakee 
Thank you for your issue. Will have a look at it asap.

**Comment by digitsensitive** [comment]
@krazyjakee Finally fixed. Thank you for reporting

https://github.com/digitsensitive/astar-typescript/pull/3
