### ISSUE TITLE
option to suppress console log?

### ISSUE THREAD

**Issue by krazyjakee** [digitsensitive/astar-typescript#4]
https://github.com/digitsensitive/astar-typescript/blob/5062cbbf7d6b3ff054d99cd5acc8f28c5604c315/lib/finders/astar-finder.ts#L78

https://github.com/digitsensitive/astar-typescript/blob/5062cbbf7d6b3ff054d99cd5acc8f28c5604c315/lib/finders/astar-finder.ts#L177

These are nasty in production.
Whether it should throw an error or return an empty array, I'm not sure. I actually prefer empty array.

**Comment by digitsensitive** [comment]
Hello @krazyjakee! Thank you for your input. I might use an environment variable for this in the future. But for now I will simply delete the console.log's.

**Comment by digitsensitive** [comment]
The version 1.1.8 is now online

**Comment by krazyjakee** [comment]
thanks very much :)
