### ISSUE TITLE
It's manhattan, not manhatten

### ISSUE THREAD

**Issue by spassvogel** [digitsensitive/astar-typescript#9]
See: https://en.wikipedia.org/wiki/Taxicab_geometry

**Comment by digitsensitive** [comment]
@spassvogel Thanks for spotting. Can you make a PR?

**Comment by spassvogel** [comment]
Sure... but it will break existing projects using `astar-typescript` .. so either you have to increase the major version or make it backwards compatible (by having both manhattan and manhatten)

**Comment by digitsensitive** [comment]
For now better have both for backwards compatible.

**Comment by digitsensitive** [comment]
@spassvogel [PR](https://github.com/digitsensitive/astar-typescript/pull/13) merged.
